version: "3.8"

services:
  # Your FastAPI application service
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb

  # MongoDB service
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
